from math import *
print("Print your values for x, y, z.")
x = int(input ("\tx = "))
y = int(input ("\ty = "))
z = int(input ("\tz = "))
a_a = (sqrt(abs(x-1)) - (abs(y))**(1/3))  /  (1+((x*x)/2)+((y*y)/4))
a_b = x*(atan(z) + exp(-(x+3)))
print("\nFor ex A:\n\ta is", a_a, "\n\tb is", a_b)
b_a = (3 + exp(y-1))/ (1+x*x*abs(y-tan(z)))
b_b = 1 + abs(y-z) + (((y-x)**2)/2) + ((abs(y-x)**3)/3)
print("\nFor ex B:\n\ta is", b_a, "\n\tb is", b_b)
c_a = (1+y)  *  (x + (y/((x*x) + 4)))  /  (exp(-x-2) + (1/((x*x) + 4)))
c_b = (1 + cos(y-2)) / ((pow(x, 4)/2) + pow(sin(z), 2))
print("\nFor ex C:\n\ta is", c_a, "\n\tb is", c_b)